### ISSUE TITLE
Malformed v2 event json on "proxy integrations for HTTP APIs" page

### ISSUE THREAD

**Issue by cpilsworth** [awsdocs/amazon-api-gateway-developer-guide#100]
Hi, 
I was looking at the [Working with AWS Lambda proxy integrations for HTTP APIs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html) page on the api gateway developer guide and I noticed that the v2 `requestContext` -> `authentication` -> `issuerDN` attribute is missing a closing quote making the event text invalid json.  The quote just needs closing after "Example issuer":
```json
"authentication": {
      "clientCert": {
        "clientCertPem": "CERT_CONTENT",
        "subjectDN": "www.example.com",
        "issuerDN": "Example issuer",
}
```

Tried to raise a PR on the project to fix as it is a small issue, but the "Edit this page on Github" link [points to a file](https://github.com/awsdocs/amazon-api-gateway-developer-guide/blob/main/doc_source/http-api-develop-integrations-lambda.md) that does not contain the recent `clientCert` changes.  Seems like the site and repo are not in sync.

**Comment by mcdwil** [comment]
Hi,

Thanks for getting in touch and pointing out the error. I've [added that file](https://github.com/awsdocs/amazon-api-gateway-developer-guide/blob/main/doc_source/http-api-develop-integrations-lambda.md) to this repo, and added the missing closing quote. The update will be published for [Working with AWS Lambda proxy integrations for HTTP APIs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.proxy-formats) soon.

Thanks,
Will
