### ISSUE TITLE
operationName field missing from the requestContext of AWS Lambda proxy integration request

### ISSUE THREAD

**Issue by fedy2** [awsdocs/amazon-api-gateway-developer-guide#109]
The `operationName` field is missing from the requestContext of the specification for the AWS Lambda proxy integration request.

**Comment by mcdwil** [comment]
Thanks for getting in touch, and sorry for the delayed response. This repo is meant for feedback and collaboration on the documentation. I'm going to go ahead and close this issue - please reopen if you have particular concerns with specific documentation pages.

**Comment by jlosito** [comment]
@mcdwil I think @fedy2 is referring to the documentation missing the $context.operationName on this [page](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html).

I believe we're missing an additional field that's denoted [here](https://github.com/aws/aws-cdk/blob/3bf6adb48a96c89455017fc0aeba97a1fe118542/packages/aws-cdk-lib/aws-apigateway/lib/method.ts#L22).
