### ISSUE TITLE
http-api-vs-rest - VPC Link to ALB support

### ISSUE THREAD

**Issue by K-Stefan** [awsdocs/amazon-api-gateway-developer-guide#114]
Hi,

I just found another very important difference between HTTP vs. REST API. The support for VPC Link to an ALB is only supported by the HTTP API. This will enable secure communication to private ALB in private subnets. 

You published also published a [blog article ](https://github.com/awsdocs/amazon-api-gateway-developer-guide/blob/main/doc_source/http-api-vs-rest.md) where you show how to configure it. 

Please reflect these differences on the documentation on [the page - https://github.com/awsdocs/amazon-api-gateway-developer-guide/blob/main/doc_source/http-api-vs-rest.md](https://github.com/awsdocs/amazon-api-gateway-developer-guide/blob/main/doc_source/http-api-vs-rest.md)

References/Links:

- https://github.com/awsdocs/amazon-api-gateway-developer-guide/blob/main/doc_source/http-api-vs-rest.md
- https://aws.amazon.com/de/blogs/compute/configuring-private-integrations-with-amazon-api-gateway-http-apis/

**Comment by mcdwil** [comment]
Hi,

Thanks for bringing this up. You’re right, private integrations directly with Application Load Balancers are supported only for HTTP APIs. [Choosing between HTTP APIs and REST APIs](https://github.com/awsdocs/amazon-api-gateway-developer-guide/blob/main/doc_source/http-api-vs-rest.md) currently covers differences at a higher level of detail. The details specific to creating private integrations are documented here for REST and HTTP APIs:

- https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-private-integration.html
- https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-private.html 


Are private integrations with Application Load Balancers a deciding factor for you when it comes to choosing between REST and HTTP APIs?

**Comment by K-Stefan** [comment]
Yes, it is. If you want to have path-based routing the way with REST API Gateway via Private Link to NLB to ALB is cumbersome.

**Comment by mcdwil** [comment]
Thanks again for reaching out. The differences have been added to [Choosing between HTTP APIs and REST APIs](https://github.com/awsdocs/amazon-api-gateway-developer-guide/blob/main/doc_source/http-api-vs-rest.md).
