### ISSUE TITLE
Customizing HTTP API access logs there is no mention of cloudwatch log retention

### ISSUE THREAD

**Issue by estebanes22** [awsdocs/amazon-api-gateway-developer-guide#115]
Customizing HTTP API access logs there is no mention of cloudwatch log retention. Any idea if this is a technical feature missing or something that needs to be adjusted in the doc? 

https://github.com/awsdocs/amazon-api-gateway-developer-guide/tree/main/doc_source/http-api-logging-variables.md

**Comment by mcdwil** [comment]
Access logs are written to the CloudWatch Logs log group that you specify. You can configure retention settings for a log group in CloudWatch: 

- https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Working-with-log-groups-and-streams.html#SettingLogRetention
- https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutRetentionPolicy.html

**Comment by estebanes22** [comment]
Thanks!
