### ISSUE TITLE
API Gateway Throttling Calculation

### ISSUE THREAD

**Issue by convexset** [awsdocs/amazon-api-gateway-developer-guide#116]
In `doc_source/api-gateway-request-throttling.md`:

> If the caller submits 5,000 requests in the first millisecond and waits until the 101st millisecond to submit another 5,000 requests, API Gateway processes 6,000 requests and throttles the rest in the one-second period. This is because at the rate of 10,000 rps, API Gateway has served 1,000 requests after the first 100 milliseconds and thus emptied the bucket by the same amount. Of the next spike of 5,000 requests, 1,000 fill the bucket and are queued to be processed. The other 4,000 exceed the bucket capacity and are discarded.

It should be that 5,500 requests are processed since:
- at 1ms: bucket is empty at 0/5000
- before 101ms: bucket is at 500/5000

**Comment by mcdwil** [comment]
Thanks for getting in touch. After discussion with the API Gateway team, I think the current example is correct.
