### ISSUE TITLE
the use of region-specific API Gateway account IDs

### ISSUE THREAD

**Issue by jastsai** [awsdocs/amazon-api-gateway-developer-guide#117]
Hi,

I am wondering what is the use of region-specific API Gateway account IDs?
for example, 

ap-southeast-2 | 798376113853

https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-api-with-vpclink-accounts.html

Thanks

**Comment by mcdwil** [comment]
Hi, thanks for reaching out. Those are API Gateway-owned accounts that are used to operate the service. They’re documented so that customers can verify that the account added as an allowed principal for their VPC endpoint service is legitimate.
