### ISSUE TITLE
Massage to all clients on websocket

### ISSUE THREAD

**Issue by harymk** [awsdocs/amazon-api-gateway-developer-guide#124]
I need sent all clients to same message. Is there any solution for that

**Comment by mcdwil** [comment]
This repo is meant for discussion and collaboration on the documentation. When you have questions about API Gateway or need expert help, I can suggest the [API Gateway forum](https://forums.aws.amazon.com/forum.jspa?forumID=199) or contacting [AWS support](https://aws.amazon.com/premiumsupport/).
