### ISSUE TITLE
Set up asynchronous invocation of the backend Lambda function Guide is outdated

### ISSUE THREAD

**Issue by notAmine** [awsdocs/amazon-api-gateway-developer-guide#125]
Hello,
the steps present in the guide [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-integration-async.html) are outdated since the API gateway is different now, is it possible to update this to hold the new steps to follow?
Thanks;

**Comment by mcdwil** [comment]
Hi,

Thanks for reaching out. Were there any specific things that you struggled with or found to be outdated?

**Comment by notAmine** [comment]
Hi,
Yes I believe since the guide was published there was a change in the API gateway UI, specifically I don't see the tabs: Method Request & Integration Request
mentioned in the steps 
`Configure Lambda asynchronous invocation in the API Gateway console

For all invocations to be asynchronous:

In Integration Request, add an X-Amz-Invocation-Type header with a static value of 'Event'.

For clients to decide if invocations are asynchronous or synchronous:

In Method Request, add an InvocationType header.

In Integration Request add an X-Amz-Invocation-Type header with a mapping expression of method.request.header.InvocationType.

Clients can include the InvocationType: Event header in API requests for asynchronous invocations or InvocationType: RequestResponse for synchronous invocations.


`

**Comment by gulshan** [comment]
I also tried to follow this instructions but UI does not match.
@notAmine and others: were you able to setup this asynchronous lambda invocation? Any idea on how to do it?

**Comment by mcdwil** [comment]
Sorry for the delayed response. I'd suggest double checking that you're using a REST API and not an HTTP API. [Set up asynchronous invocation of the backend Lambda function](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-integration-async.html) has also recently been updated to include more examples. Hope that helps!

**Comment by notAmine** [comment]
Oh good to know I'm way past that project now but thanks for the closure :)
