### ISSUE TITLE
Link to get-client-certificate of AWS CLI is outdated

### ISSUE THREAD

**Issue by bdb2381** [awsdocs/amazon-api-gateway-developer-guide#130]
The section _Configure a backend HTTPS server to verify the client certificate_ links to CLI v1 (https://docs.aws.amazon.com/cli/latest/reference/apigateway/get-client-certificate.html)

I suspect it should link to CLI v2 (https://awscli.amazonaws.com/v2/documentation/api/latest/reference/apigateway/get-client-certificate.html) ?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
