### ISSUE TITLE
HTTP API Parameter Mapping doc, wrongfully states body can be transformed

### ISSUE THREAD

**Issue by soulasvalentin** [awsdocs/amazon-api-gateway-developer-guide#134]
The first paragraph under **Transforming API requests** section of the [HTTP API Parameter mapping doc](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-parameter-mapping.html) says the following:

> You use request parameters to change requests before they reach your backend integrations. You can modify headers, query strings, the request path, or the request body.

Notice how at the end, it's stated that the request body is transformable. This is then refused by the **Parameter mapping keys** table which does not include the request body as transformable key. 

I also tried this through an actual AWS HTTP API and noticed that the available parameters to modify are the same as the ones mentioned in the table.

![image](https://user-images.githubusercontent.com/11997704/128886023-ef48a818-5fbb-471f-8c78-24b4b71dcb2c.png)

This is also backed by the [HTTP vs REST doc](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html) which mentions that request body transformations are not supported in HTTP APIs.

![image](https://user-images.githubusercontent.com/11997704/128886869-012c6cfa-885f-4735-a30d-9c81674b7466.png)

-------------

I'm happy to create the PR myself but I'd like if someone can verify my analysis is correct.

**Comment by mcdwil** [comment]
Thanks for taking the time to submit an issue. Your analysis is correct. I've [updated the docs accordingly](https://github.com/awsdocs/amazon-api-gateway-developer-guide/commit/32e149d833f773ae1684bf57165c093f8f39e0b7#diff-8f44f3ad6316e0bb1767adba0c92e062582ab122ae7104dea2625ec8de8ab56d).
