### ISSUE TITLE
Update JSON to YAML for API Gateway resource policy examples 

### ISSUE THREAD

**Issue by PhillypHenning** [awsdocs/amazon-api-gateway-developer-guide#141]
The document for adding policies to a API gateway only has JSON examples ... It would be helpful to update the second example blocks with the yaml equivalent.

**Comment by mcdwil** [comment]
Thanks for taking the time to submit feedback on our documentation. We're always working to improve it, and your feedback helps us know where to focus our efforts. Some tools such as CloudFormation and SAM support YAML, but the resource policy [must be JSON](https://docs.aws.amazon.com/apigateway/latest/api/API_CreateRestApi.html#apigw-CreateRestApi-request-policy) at the API level.
