### ISSUE TITLE
Steps are not cleared for API Gateway integration 

### ISSUE THREAD

**Issue by mansurali901** [awsdocs/amazon-api-gateway-developer-guide#153]
it seems like documentation is not comprehensive lots of steps and information are missing.

- No information about IAM role which service to be choose as source service 
- No information either we need to create Internal NLB or internet-facing NLB
-

**Comment by mcdwil** [comment]
Thanks for taking the time to submit feedback on our documentation. We're always working to improve it, and your feedback helps us know where to focus our efforts.
