### ISSUE TITLE
The token payload is modified before being passed to event.requestContext.authorizer.claims

### ISSUE THREAD

**Issue by marceliwac** [awsdocs/amazon-api-gateway-developer-guide#158]
There is no documentation on the format of the `event.requestContext.authorizer.claims`, as provided by the API Gateway Cognito Authorizer. This is a problem, because one would expect the payload of the JWT (token) to be the same in both the encoded token itself, and the contents of `event.requestContext.authorizer.claims` provided to the lambda integration.

The disparity in these values can be seen in any logs, because all of the values of the token's payload in the `event.requestContext.authorizer.claims` are strings (as opposed to actual values (numbers, arrays, timestamps etc. in the JWT payload), resulting in the need to parse these manually when working with cognito authorizer.

I have outlined this issue better in this [StackOverflow post](https://stackoverflow.com/questions/74180027/why-does-aws-api-gateway-cognito-authroizer-change-the-jwt-payload-in-extracted).

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
