### ISSUE TITLE
VPC Endpoint and public DNS names ?

### ISSUE THREAD

**Issue by tbriot** [awsdocs/amazon-api-gateway-developer-guide#16]
In the section "**How to Invoke a Private API**":
> 3. In the Details pane, you'll see **4 values** in the DNS names field. **The first 2** are the private DNS names for your API. **The other 2** are the public DNS names for it.

Does not look like the Details pane displays those 2 private and 2 public DNS names.

I see one DNS name for the VPC Endpoint (that resolves to a private IP, even outside of the AWS cloud).
Plus additional DNS names for each AZ (resolves to private IPs too).

I'm confused.
See attached screenshot: [VPC Endpoint Details](https://i.imgur.com/rjZSB7f.png)

**Comment by dianeo** [comment]
Sorry, I've been unable to reproduce the problem. Please try the AWS Developer Forum for API Gateway: https://forums.aws.amazon.com/forum.jspa?forumID=199&start=0
