### ISSUE TITLE
"API developer" in "AWS Gateway concepts" is confusing

### ISSUE THREAD

**Issue by marios-zindilis** [awsdocs/amazon-api-gateway-developer-guide#167]
In the [AWS Gateway concepts](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-basic-concept.html), the "API developer" is defined as:

> **API developer**
>
> Your AWS account that owns an API Gateway deployment (for example, a service provider that also supports programmatic access).

In the previous page, [API Gateway use cases](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-overview-developer-experience.html), we see:

> An API developer creates and deploys an API to enable the required functionality in API Gateway. The API developer must be a user in the AWS account that owns the API.

Isn't this confusing? Is the API developer a user or an account?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
