### ISSUE TITLE
"Callback URL" in "AWS Gateway concepts" wording

### ISSUE THREAD

**Issue by marios-zindilis** [awsdocs/amazon-api-gateway-developer-guide#168]
In the [AWS Gateway concepts](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-basic-concept.html), we see the "Callback URL" defined as:

> **Callback URL**
>
> When a new client is connected to through a WebSocket connection, you can call an integration in API Gateway to store the client's callback URL. You can then use that callback URL to send messages to the client from the backend system.

This sentence feels like it is either missing something after "to", e.g. "client is connected to *something* through a WebSocket", or "to" is extraneous.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
