### ISSUE TITLE
Small inaccuracies in "Tutorial: Build an API Gateway REST API with Lambda non-proxy integration"

### ISSUE THREAD

**Issue by marios-zindilis** [awsdocs/amazon-api-gateway-developer-guide#169]
In [Tutorial: Build an API Gateway REST API with Lambda non-proxy integration](https://docs.aws.amazon.com/apigateway/latest/developerguide/getting-started-lambda-non-proxy-integration.html), in the "Clean up" section, we see some inaccuracies:

* When deleting the Lambda functions:

    > From the list of functions, choose **GetHelloWorld**

     ...but no such Lambda function was created in this tutorial or in any of the previous ones.

* Also when deleting the Lambda functions:

    > From the list of functions, choose **GetHelloWithName**

    ...but no such Lambda function was created in this tutorial or in any of the previous ones.

* Similarly, when deleting the IAM resources the user is asked to select the role named **APIGatewayLambdaExecRole** and the policy named **APIGatewayLambdaExecPolicy**, but no such role or policy were created during the tutorial.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
