### ISSUE TITLE
Possible error in type for requestParams for PostToConnectionCommand

### ISSUE THREAD

**Issue by schuettc** [awsdocs/amazon-api-gateway-developer-guide#173]
https://github.com/awsdocs/amazon-api-gateway-developer-guide/blob/main/doc_source/apigateway-how-to-call-websocket-api-connections.md

Shows:

```
  const requestParams = {
    ConnectionId: connectionId,
    Data: "Hello!",
  };

  const command = new PostToConnectionCommand(requestParams);
```

However, it appears that Data should be a Unit8Array:

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-apigatewaymanagementapi/interfaces/posttoconnectionrequest.html

And not a string.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
