### ISSUE TITLE
gateway API has slightly different parameters than example shown

### ISSUE THREAD

**Issue by peter8472** [awsdocs/amazon-api-gateway-developer-guide#18]
For example, callerName doesn't appear anywhere in the code, but it is accepted in a POST body at '(https://)r275xc9bmd.execute-api.us-west-2.amazonaws.com/test/Seattle?time=evening'

Also the "time" parameter is only accepted in a request-body, not as shown in a query string.  (The documentation correctly reports the results as "good **day"**)

Anyways... is the code running at (https://)r275xc9bmd.execute-api.us-west-2.amazonaws.com publicly available?

**Comment by dianeo** [comment]
No, it isn't publicly available. The tutorial in question has now been rewritten, so the parameters should now work correctly.
