### ISSUE TITLE
Document missing swagger extension minimum-compression-size

### ISSUE THREAD

**Issue by danopz** [awsdocs/amazon-api-gateway-developer-guide#2]
We've just figured out there is a way to define the minimum compression size using the ApiGateway Import API with a swagger file using the swagger extension `x-amazon-apigateway-minimum-compression-size`. It would be nice if this would be documented side-by-side with the other swagger extensions.

**Comment by dianeo** [comment]
Sorry for the slow response. I'm adding this to the API Gateway doc backlog so it will get addressed. Thanks!

**Comment by LinusU** [comment]
@dianeo any updates on this? It still doesn't seem to be documented and it took me quite a while to figure out how to set it 😬 

I believe that this would be the correct page to add it to:

https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions.html
