### ISSUE TITLE
"Principal " needs clarity - Is "IAM Role" included

### ISSUE THREAD

**Issue by sringopi** [awsdocs/amazon-api-gateway-developer-guide#21]
Here is the description of "Principal" in Access Policy for API Gateway

> _Principal  – The account or user who is allowed access to the actions and resources in the statement. In a resource policy, the principal is **the IAM user or account** who is the recipient of this permission_

Needs to clarify if the principal can be an **IAM Role**.  If yes, it should read as:

> _Principal – The account or user who is allowed access to the actions and resources in the statement. In a resource policy, the principal is **the IAM user, role or account** who is the recipient of this permission_

**Comment by dianeo** [comment]
I think the docs are reasonably clear on this point.
