### ISSUE TITLE
Output is wrong when testing API  

### ISSUE THREAD

**Issue by eugene-xie** [awsdocs/amazon-api-gateway-developer-guide#22]
[Build an API Gateway API with Lambda Proxy Integration](https://github.com/awsdocs/amazon-api-gateway-developer-guide/blob/master/doc_source/api-gateway-create-api-as-simple-proxy-for-lambda.md) says you will get the following response when you test it with cURL:

> "message": "Good day, **John** of Seattle. Happy Friday!",

but actually you will get

> "message": "Good day, **you** of Seattle. Happy Friday!",

Although the request body has "callerName": "John", it isn't used.

**Comment by dianeo** [comment]
This tutorial has been rewritten and should now be correct.
