### ISSUE TITLE
"Map Request Parameters for an API Gateway API" Errors

### ISSUE THREAD

**Issue by drguildo** [awsdocs/amazon-api-gateway-developer-guide#24]
Following the steps in _Map Request Parameters for an API Gateway API_ as part of `api-gateway-create-api-step-by-step.md`, when I get to creating the `GET` method for `http://petstore-demo-endpoint.execute-api.com/petstore/pets/{id}` and mapping `method.request.path.petId` to `id` I get the error:

```
Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping expression parameter specified: method.request.path.petId]
```

I've tried swapping the parameter names around but still get the same error.

I also get the following warnings next to the endpoint URL:

```
The endpoint you have entered does not contain all of the path parameters for the resource. You can include path parameters by surrounding them in curly braces (eg. {resourceId})
```

```
The endpoint you have entered contains parameters that are not defined in the resource path. Parameters are case sensitive.
```

**Comment by dianeo** [comment]
Sorry, I've been unable to reproduce the problem. You might want to try the AWS Developer Forum for API Gateway: https://forums.aws.amazon.com/forum.jspa?forumID=199&start=0
