### ISSUE TITLE
No info on available @connections commands for Websocket API

### ISSUE THREAD

**Issue by eudes** [awsdocs/amazon-api-gateway-developer-guide#27]
The [page on "@connections Commands"](https://github.com/awsdocs/amazon-api-gateway-developer-guide/blob/master/doc_source/apigateway-how-to-call-websocket-api-connections.md) states:
> Your backend service can use the following WebSocket connection HTTP requests to **send a callback message to a connected client, get connection information, or disconnect the client**.

It goes on to describe the **callback message** procedure, but no further info is given on how to get connection information or how to disconnect the client from the backend.

I found this issue (https://github.com/aws-samples/simple-websockets-chat-app/issues/10) that states an HTTP DELETE request should be sent to the endpoint for terminating connections.

It would be useful to have more information about the available commands and how to execute them.

**Comment by sergey-rud** [comment]
I agree. Documentation is seriously flawed. Also I cannot find any documentation about what responses will be returned in different cases:
1) Message successfully sent (200)
2) Message sent to non-existing connectionId (403)
3) Message sent to closed connectionId (410)
4) What response would be if we sent message to @connections API and forget to encode @ character (504)
5) etc.

**Comment by dianeo** [comment]
I think this link will help: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/apigatewaymanagementapi.html

**Comment by aleclarson** [comment]
@dianeo How is that link meant to help? Can you point to where it talks about [the `@connections` endpoint](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-how-to-call-websocket-api-connections.html)?
