### ISSUE TITLE
Websocket API: Not clear how to set up Mapping Templates for Integration Requests

### ISSUE THREAD

**Issue by eudes** [awsdocs/amazon-api-gateway-developer-guide#28]
This is a problem with both the documentation and the UI: it's not clear how to set up a mapping template for a particular Integration Request in the Websocket API console.

I tried to create a Mapping Template for the $connection route in order to add the context variables to the Integration Request in an HTTP integration.

In my case, the UI requires you to:
* create the route, selecting HTTP integration, and **deselecting Use HTTP Proxy integration**.
* save
* open the Request Templates collapsible (which wasn't there until you save)
* save a Template selection expression
* click on "add a request template"
* add a request template **key**
* and **finally** see the Mapping Template textarea

This is not detailed in the documentation, and it should definitely be. It's confusing from beginning to end.

**Comment by dianeo** [comment]
Sorry for the slow reply. I'm adding this to the API Gateway doc backlog so it will be addressed soon. Thanks!

**Comment by codeasashu** [comment]
@dianeo why is the issue closed? its only in the backlog but its not yet resolved. IMHO, issues should be closed with a commit mentioning the fixes and not just abruptly without addressing how/when the issue will be solved
