### ISSUE TITLE
Websocket API: include documentation about the API Gateway Management API libraries

### ISSUE THREAD

**Issue by eudes** [awsdocs/amazon-api-gateway-developer-guide#29]
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-how-to-call-websocket-api-connections.html

The `@connections` REST endpoint can be accessed through the API Gateway Management API library. There's no mention of this library anywhere in the Websocket documentation. This library takes care of signing and generating the REST requests necessary to send messages through the websocket.

There's no mention of the library anywhere.

Please add a reference to it. I had to cook my own SigV4 URL signer, which a wasn't particularly pleasant task.

**Comment by dianeo** [comment]
Added. I'll publish the update later this week.
