### ISSUE TITLE
I dont find `Client Side Cert` option in Testing the API

### ISSUE THREAD

**Issue by RameshRM** [awsdocs/amazon-api-gateway-developer-guide#3]
Hi ,

Your document has a screen for setting "ClientCert" for Testing, I dont see any option in Testing section can you clarify ?

https://docs.aws.amazon.com/apigateway/latest/developerguide/getting-started-client-side-ssl-authentication.html#test-invoke

**Comment by tbriot** [comment]
I do see that **Client Certificate** option on the **Test** page.
Checked in Canada (Central) and Asia Pacific (Mumbai) regions. Looks good to me.

@RameshRM: In what region is your API ?

**Comment by dianeo** [comment]
@tbriot is correct. The Client Certificate option should appear in the Method Test pane, assuming you have a client certificate
