### ISSUE TITLE
Dead GitHub link in the online documentation

### ISSUE THREAD

**Issue by AdrienFromToulouse** [awsdocs/amazon-api-gateway-developer-guide#4]
Hi,

I noticed a dead link in the online documentation.

How to reproduce:

- Go to <https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-override-request-response-parameters.html>

- Click on the `GitHub` icon in the header (next to the PDF one)
<img width="1384" alt="screen shot 2018-07-14 at 10 32 25" src="https://user-images.githubusercontent.com/1558229/42722752-f45994aa-8751-11e8-89b1-97e69417e0fa.png">

- The user agent is redirected to:
https://github.com/awsdocs/amazon-api-gateway-developer-guide/tree/master/doc_source/apigateway-override-request-response-parameters.md

- The result is a `404`:
<img width="958" alt="screen shot 2018-07-14 at 10 38 57" src="https://user-images.githubusercontent.com/1558229/42722766-26fd6bf2-8752-11e8-97ef-faa9d17872d8.png">

Cheers!

**Comment by tbriot** [comment]
Works fine for me.
@AdrienFromToulouse: do you still have this issue ?

Maybe related to #8.

**Comment by AdrienFromToulouse** [comment]
@tbriot it is fixed now.
