### ISSUE TITLE
out of date docs

### ISSUE THREAD

**Issue by craftdelivery** [awsdocs/amazon-api-gateway-developer-guide#41]
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html

this article seems to be out of date. Many of these steps are non-existant in the AWS API Gateway console. Specifically steps 16-20

**Comment by mcdwil** [comment]
@craftdelivery - thanks for bringing this up. The topic has been updated to match the console. https://github.com/awsdocs/amazon-api-gateway-developer-guide/commit/b2669a27cf35c456223ab09b20d47b64b9cc391#diff-cefea377040278f765a07af6568442a1
