### ISSUE TITLE
Please document HTTP API Lambda with AWS CDK

### ISSUE THREAD

**Issue by bionicles** [awsdocs/amazon-api-gateway-developer-guide#52]
How do you use CDK to make HTTP APIs with Lambda functions?

Just want to do Serverless with CDK because CDK is way simpler than Cloudformation and HTTP api is way simpler than REST api but no infrastructure as code tools support this use case

Here is a great spot for an example:

https://github.com/aws-samples/aws-cdk-examples

**Comment by mcdwil** [comment]
Thanks for reaching out. I'm sorry to hear that you're having trouble using the CDK. It looks like there's already an [open issue](https://github.com/aws-samples/aws-cdk-examples/issues/212) in the repo that you linked to, so I'm going to resolve this issue in favor of that one.
