### ISSUE TITLE
Clarifications on using aws-amplify

### ISSUE THREAD

**Issue by adityats2020** [awsdocs/amazon-api-gateway-developer-guide#60]
According to [this](https://github.com/aws-amplify/amplify-js/issues/5067) post on amplify github, amplify is only meant for use cases with AWS Cognito. The AWS Docs are not clear about this, and seems to indicate that amplify can be used with or without Cognito: https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-call-api-using-aws-amplify-javascript-library.html

**Comment by mcdwil** [comment]
Hi, 

Thanks for the feedback. I'm sorry to hear that you found the docs unclear. I've [updated the topic](https://github.com/awsdocs/amazon-api-gateway-developer-guide/commit/d02edad0d456cdb79a2961b1b9dd487bb1d1d790#diff-31bdd6626b403dfed4e26f18337f035a).

Thanks,
Will
