### ISSUE TITLE
Mapping value error does not disappear when mapping value is corrected which can mislead user into thinking the updated value is wrong

### ISSUE THREAD

**Issue by sid2121** [awsdocs/amazon-api-gateway-developer-guide#7]
Let's say I want to set header mappings for a 'post' method.
I set the value of Response header to be Access-Control-Allow-Origin and mapping value "*".
It throws an error: 'Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping expression specified: "*"]'. Now I change the mapping value to '*' which fixes the error. But the error is still hanging up there in the console which misleads the user into thinking the fix is wrong.

**Comment by dianeo** [comment]
This is a console bug, not a documentation bug. Please report it in the AWS forum for API Gateway. Thanks! https://forums.aws.amazon.com/forum.jspa?forumID=199
