### ISSUE TITLE
Typo in request header name

### ISSUE THREAD

**Issue by pglezen** [awsdocs/amazon-api-gateway-developer-guide#71]
At the end of the sample, the `curl` invocation adds the following request header.

```
-H 'x-amnz-RequestId:123344566'
```

First of all, I'm not sure why an inbound request would even have this (perhaps simulating another AWS service?).  But in any case, the `amnz` portion should probably be `amzn`.  It causes the `x-amzn-request` in the response to be overridden, which I believe was the intended effect.

I didn't include a pull request for the typo because fixing the type also impacts the response of the curl command.  I don't have PetStore installed to definitively determine the correct response.  Just for illustration purposes, here is the difference on my sample API.

### Misspelled Header

In this case, the `x-amzn-requestid` response header was the usual UUID format.

```
$ curl  -H "x-amnz-RequestId:12345678" https://api-dev.sample.org/abc -i
HTTP/2 404
date: Fri, 17 Apr 2020 15:17:12 GMT
content-type: application/json
content-length: 146
x-amzn-requestid: 68c4fad4-ca27-49cb-a46d-9603999d8ea2
x-amzn-errortype: MissingAuthenticationTokenException
x-amz-apigw-id: LIxCyGd7SK4FjEg=
```

### Corrected Header

In this case, `x-amzn-requestid` reflects the input request header.

```
$ curl  -H "x-amzn-RequestId:12345678" https://api-dev.sample.org/abc -i
HTTP/2 404
date: Fri, 17 Apr 2020 15:16:34 GMT
content-type: application/json
content-length: 146
x-amzn-requestid: 12345678
x-amzn-errortype: MissingAuthenticationTokenException
x-request-id: 12345678
x-amz-apigw-id: LIw84EkUSK4FUcA=
```

**Comment by mcdwil** [comment]
Hi,

Thanks for pointing this out. You're right, the `curl` example should use `x-amzn-RequestId`. When the header is spelled correctly, the response includes the provided value in `x-amzn-RequestId`. I'll update the `curl` example and response.

Thanks,
Will

**Comment by mcdwil** [comment]
Thanks again for getting in touch! The [examples are updated](https://github.com/awsdocs/amazon-api-gateway-developer-guide/commit/d02edad0d456cdb79a2961b1b9dd487bb1d1d790#diff-bece47c126bc00a5a24a4e8e3affe568).
