### ISSUE TITLE
Dead GitHub link

### ISSUE THREAD

**Issue by abhilash1in** [awsdocs/amazon-api-gateway-developer-guide#8]
The corresponding [GitHub link](https://github.com/awsdocs/amazon-api-gateway-developer-guide/tree/master/doc_source/apigateway-private-apis.md) for the [Create a Private API in Amazon API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-apis.html) documentation page is missing/broken.

**Comment by tbriot** [comment]
Works fine for me. I was able to submit two PR today.
@abhilash1in: do you still have this issue ?

**Comment by dianeo** [comment]
Looks like it's working.

**Comment by abhilash1in** [comment]
Was broken when it was reported. Looks fine now.
