### ISSUE TITLE
possible to authorize "any" client with JWT-authorizer

### ISSUE THREAD

**Issue by devdavidkarlsson** [awsdocs/amazon-api-gateway-developer-guide#89]
It seems to me that the JWT-authorizer in a HTTP-api on AWS API-Gateway does not support adding "any client" as allowed audience.

I think this becomes a problem in the case you want to use it for an API where clients get added removed a lot (or when many clients are to be supported).

Am I missing something (an asterix or something in the configuration), or can't the JWT-authorizer support such cases where clients are added/removed dynamically outside of the IAC?

I am reading the docs [here](https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/apis-apiid-authorizers-authorizerid.html#apis-apiid-authorizers-authorizerid-model-jwtconfiguration): 

_**Audience : Required for the JWT authorizer type**_

**Comment by mcdwil** [comment]
Hi, thanks for getting in touch and sorry for the delayed response. Currently, clients must be specified in the `audience` for a JWT authorizer. I'll pass your feedback along to the engineering team.
