### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by abhilash1in** [awsdocs/amazon-api-gateway-developer-guide#9]
In [Create a Private API in Amazon API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-apis.html):

> If you choose to enable private DNS, you'll be able **to to** access your API via private or public DNS

Could not find the corresponding page on GitHub to submit a PR. 

awsdocs/amazon-api-gateway-developer-guide/issues/8

**Comment by tbriot** [comment]
Submitted a PR #17.

**Comment by dianeo** [comment]
Fixed, thanks!
